### ISSUE TITLE
option --json_config does not work

### ISSUE THREAD

**Issue by ttarczynski** [sensu-plugins/sensu-plugins-hipchat#3]
I've checked options for `handler-hipchat.rb` in help:

```
# /opt/sensu/embedded/bin/handler-hipchat.rb --help
Usage: /opt/sensu/embedded/bin/handler-hipchat.rb (options)
    -j, --json_config JsonConfig     Config Name
```

When I use the `--json_config` option I get the following error:

```
# cat /tmp/sensu_event | /opt/sensu/embedded/bin/handler-hipchat.rb --json_config  /etc/sensu/conf.d/handlers/hipchat.json
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:134:in `block in filter_silenced': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:134:in `block in filter_silenced': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:134:in `block in filter_silenced': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-hipchat-0.0.3/bin/handler-hipchat.rb:43:in `handle': undefined method `[]' for nil:NilClass (NoMethodError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:55:in `block in <class:Handler>'
```

I've found a workaround here: [How to Get Sensu Hipchat Plugin to Work](http://www.ahwkong.com/post/2015/02/28/how-to-get-sensu-hipchat-plugin-to-work/)
When I use this handler without the `--json_config` option it works OK, but I still think this issue needs a fix.

---

My environment:

``` bash
# cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 

# rpm -q sensu
sensu-0.23.2-1.x86_64

# /opt/sensu/embedded/bin/ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```
- `/etc/sensu/conf.d/handlers/hipchat.json`

``` json
# cat /etc/sensu/conf.d/handlers/hipchat.json
{ 
  "handlers": {
    "hipchat": {
      "command": "/opt/sensu/embedded/bin/handler-hipchat.rb -j /etc/sensu/conf.d/handlers/hipchat.json",
      "type": "pipe",
      "filters": [

      ],
      "severities": [
        "ok",
        "warning",
        "critical",
        "unknown"
      ]
    }
  },
  "hipchat": {
    "apikey": "<key>",
    "apiversion": "v1",
    "room": "sensu",
    "from": "Sensu"
  }
}
```

**Comment by ttarczynski** [comment]
I've found how the `--json_config` option works:
- all sensu json configuration is loaded and merged as described in [How does Sensu load configuration?](https://sensuapp.org/docs/latest/configuration#how-does-sensu-load-configuration)
  - configuration file (`/etc/sensu/config.json` by default)
  - configuration directory (`/etc/sensu/conf.d/` by default)
- handlers configuration is loaded and merged using [lib/sensu-plugin/utils.rb](https://github.com/sensu-plugins/sensu-plugin/blob/master/lib/sensu-plugin/utils.rb) from all `.json` config files:
  - `['/etc/sensu/config.json']`
  - `Dir['/etc/sensu/conf.d/**/*.json']`
- the `.json` file name is irrelevant
- handler configuration is loaded from the particular json key name which is `hipchat` by default and can be changed with `--json_config` option

I've also seen someone had a similar issue here: [sensu-users › Banging my head to get mail working.](https://groups.google.com/forum/#!msg/sensu-users/BI1VVqSou-8/Edyt-H6EBgAJ)
I think some documentation fix would help here. I will try to prepare a pull request.

**Comment by eheydrick** [comment]
Fixed via #4.

**Comment by bobbychef64** [comment]
does this worked ?

**Comment by bobbychef64** [comment]
I am seeing this error 
ruby handler-hipchat.rb 
/usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sensu-handler (LoadError)
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from handler-hipchat.rb:25:in `<main>'

**Comment by bobbychef64** [comment]
If this is issue is resolved kindly let me know

**Comment by eheydrick** [comment]
Hi @bobbychef64, that issue looks different from the one in the original issue. Would you mind opening a new issue. That said, it looks like you don't have the `sensu-plugin` gem installed. Can you check the gems you have installed in that ruby installation. Also, if possible you should use the embedded ruby that ships with sensu.
