### ISSUE TITLE
Object#timeout is deprecated, use Timeout.timeout instead.

### ISSUE THREAD

**Issue by caskolkm** [sensu-plugins/sensu-plugins-hipchat#5]
`handler-hipchat.rb:68:in`handle': Object#timeout is deprecated, use Timeout.timeout instead.`

See also https://github.com/sensu-plugins/sensu-plugins-mailer/issues/21

**Comment by cwjohnston** [comment]
This will be solved with the next release, as the change to sensu-plugin dependency enables use with newer versions of that library which no longer generate these deprecation warnings.

**Comment by majormoses** [comment]
This can be solved easily without waiting to bump deps (might already be done) and is a one line fix.

**Comment by majormoses** [comment]
closing per: https://github.com/sensu-plugins/sensu-plugins-hipchat/issues/5#issuecomment-238950160
